details:
  namespace: student68-bookinfo-uat
  image: ghcr.io/sharkthoven/bookinfo-details
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.uat.opsta.net
  path: "/student68/details(/|$)(.*)"
  serviceType: ClusterIP